//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 sadpdlg.rc 使用
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SADPDLG_DIALOG              102
#define IDD_HCPLATFORMSTATUS            103
#define IDR_MAINFRAME                   128
#define IDD_DLG_HIKSADP                 129
#define IDB_BITMAP1                     130
#define IDD_RESET_PASSWORD              131
#define IDD_DIALOG_CUSTOM               135
#define IDD_DLG_SECURITY_QUESTION       136
#define IDD_DLG_BIND_DEV_LIST           137
#define IDD_WIFI_GEGION                 138
#define IDD_DLG_SELF_CHECK              139
#define IDD_DIALOG1                     140
#define IDD_CONFIG_DLG                  140
#define IDD_DLG_EHOME_ENABLE            141
#define IDD_DLG_MAIL_BOX_RESET_PW       142
#define IDD_DLG_UNBIND                  143
#define IDD_DLG_UNBIND_DEL_USER         144
#define IDD_DLG_SET_AUTOREQ_INTERVAL    145
#define IDD_DLG_SET_FILTER_RULE         146
#define IDD_DLG_ACTIVATE_DEVICE         148
#define IDD_DIALOG2                     149
#define IDD_DLG_RESTORE_INACTIVE        149
#define IDD_DLG_RESET_GUID              150
#define IDD_DLG_REST_PW_ENCRYPT         151
#define IDD_DLG_REST_PW_DEVICE_CODE     152
#define IDD_DLG_EZVIZ_TOKEN             153
#define IDD_DLG_RESET_PHONE             154
#define IDD_DIG_INQUIRY_SUBNET          155
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_SELECT_DEV           1000
#define IDC_BTN_RESET_PASSWORD          1000
#define IDC_BTN_GET                     1000
#define IDC_BTN_GET_QUESTION            1000
#define IDC_LIST1                       1001
#define IDC_LIST_DEV_INFO               1001
#define IDC_ANSWER_RESET_PASSWORD       1001
#define IDC_BTN_GUID_RESET_PASSWORD     1001
#define IDC_BUTTON8                     1001
#define IDC_BUTTON_OK                   1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_BACK                 1002
#define IDC_BTN_EXPORT_FILE             1002
#define IDC_BTN_SET_QUESTION            1002
#define IDC_BTN_GETSTATUS               1002
#define IDC_BUTTON3                     1003
#define IDC_BUTTON_MODIFY               1003
#define IDC_BTN_IMPORT_FILE             1003
#define IDC_BUTTON_UNBIND               1003
#define IDC_BUTTON4                     1004
#define IDC_BUTTON_CANSEL               1004
#define IDC_BTN_EXPORT_GUID             1004
#define IDC_BUTTON5                     1005
#define IDC_BUTTON_SAFE                 1005
#define IDC_BTN_SECURITY_QUESTION       1005
#define IDC_EDIT1                       1006
#define IDC_EDIT_DEV_SN                 1006
#define IDC_EDIT_INPUT_STRING           1006
#define IDC_EDIT_DEV_UNLOCK_CODE        1006
#define IDC_EDIT_ID1                    1006
#define IDC_EDIT_DEV_ID                 1006
#define IDC_EDIT2                       1007
#define IDC_EDIT_SOFT_VERSION           1007
#define IDC_EDIT_IMPORT_FILE            1007
#define IDC_EDIT_SECRET_KEY             1007
#define IDC_EDIT_ANSWER1                1007
#define IDC_EDIT_INPUT_PASSWORD         1007
#define IDC_EDIT_VERIFICATION_CODE      1007
#define IDC_EDIT_EHOME_KEY              1007
#define IDC_EDIT_COMMAND                1007
#define IDC_EDIT_DEV_SERIAL_NO          1007
#define IDC_IPADDRESS1                  1008
#define IDC_IPADDRESS_MASK              1008
#define IDC_EDIT_CUSTOM_TYPE            1008
#define IDC_EDIT_ID2                    1008
#define IDC_BTN_IMPORT_GUID             1008
#define IDC_IPADDRESS_START_IP          1008
#define IDC_IPADDRESS2                  1009
#define IDC_IPADDRESS_ADDR              1009
#define IDC_EDIT_SECRET_KEY_TEMP        1009
#define IDC_EDIT_ANSWER2                1009
#define IDC_BTN_RESET_PASSWORD2         1009
#define IDC_IPADDRESS_STOP_IP           1009
#define IDC_EDIT3                       1010
#define IDC_EDIT_PORT                   1010
#define IDC_EDIT_ID3                    1010
#define IDC_EDIT_PASS_WORD              1010
#define IDC_EDIT4                       1011
#define IDC_EDIT_MAC                    1011
#define IDC_EDIT_ANSWER3                1011
#define IDC_EDIT_PASS_WORD2             1011
#define IDC_EDIT_CHANNEL_DEFAULT_PW     1011
#define IDC_EDIT5                       1012
#define IDC_EDIT_PASSWORD               1012
#define IDC_EDIT_ID4                    1012
#define IDC_STATIC_PSWINPUT             1013
#define IDC_EDIT_ANSWER4                1013
#define IDC_EDIT_RESET_PASSWORD         1013
#define IDC_STATIC_TIP                  1014
#define IDC_EDIT_HTTP_PORT              1014
#define IDC_EDIT_ID5                    1014
#define IDC_STATIC_ID                   1015
#define IDC_EDIT_ANSWER5                1015
#define IDC_STATIC_VERSION              1016
#define IDC_EDIT_ID6                    1016
#define IDC_STATIC_MASK                 1017
#define IDC_EDIT_ANSWER6                1017
#define IDC_STATIC_IP                   1018
#define IDC_EDIT_ID7                    1018
#define IDC_STATIC_PORT                 1019
#define IDC_EDIT_ANSWER7                1019
#define IDC_STATIC_MAC                  1020
#define IDC_EDIT_ID8                    1020
#define IDC_STA_STATE                   1021
#define IDC_EDIT_ANSWER8                1021
#define IDC_BUTTON6                     1022
#define IDC_BUTTON_DEFAULT_PW           1022
#define IDC_EDIT_ID9                    1022
#define IDC_EDIT6                       1023
#define IDC_EDIT_DEFAULT_PW             1023
#define IDC_EDIT_ANSWER9                1023
#define IDC_STATIC_MODIFYPSWD           1024
#define IDC_EDIT_ID10                   1024
#define IDC_EDIT_IPv6_ADDRESS           1025
#define IDC_EDIT_ANSWER10               1025
#define IDC_EDIT_IPv6_GATEWAY           1026
#define IDC_EDIT_ID11                   1026
#define IDC_IPADDRESS_GATEWAY           1027
#define IDC_EDIT_ANSWER11               1027
#define IDC_EDIT_MASK_LEN               1028
#define IDC_EDIT_ID12                   1028
#define IDC_EDIT_DESCRIPTION            1029
#define IDC_EDIT_ANSWER12               1029
#define IDC_BUTTON_DEFAULT_PW2          1030
#define IDC_STATIC_HTTP_PORT            1030
#define IDC_EDIT_ID13                   1030
#define IDC_EDIT_OEM_INFO               1031
#define IDC_BTN_ACTIVATE_DEVICE         1031
#define IDC_EDIT_ANSWER13               1031
#define IDC_EDIT_ACTIVATE_PASSWORD      1032
#define IDC_EDIT_ID14                   1032
#define IDC_BTN_RESET_PW                1033
#define IDC_EDIT_ANSWER14               1033
#define IDC_EDIT_ID15                   1034
#define IDC_STATIC_HTTP_PORT2           1034
#define IDC_EDIT_ANSWER15               1035
#define IDC_EDIT_HTTP_PORT2             1035
#define IDC_EDIT_TLS_PORT               1035
#define IDC_EDIT_INPUT_PASSWORD2        1036
#define IDC_BTN_RESET_PW2               1036
#define IDC_BTN_RESET_PW3               1037
#define IDC_EDIT_ID16                   1037
#define IDC_BTN_RESET_PW4               1038
#define IDC_EDIT_ANSWER16               1038
#define IDC_CHECK_DHCP                  1039
#define IDC_EDIT_ID17                   1039
#define IDC_BUTTON_ENTRY                1040
#define IDC_EDIT_ANSWER17               1040
#define IDC_LIST_SUBNET_DEV_INFO        1040
#define IDC_STATIC_PUID                 1041
#define IDC_EDIT_ID18                   1041
#define IDC_EDIT_PUID                   1042
#define IDC_EDIT_ANSWER18               1042
#define IDC_STATIC_PW                   1043
#define IDC_EDIT_PW                     1044
#define IDC_STATIC_IPv4                 1045
#define IDC_STATIC_IPv6                 1046
#define IDC_STATIC_PUID2                1047
#define IDC_EDIT_IPv6                   1048
#define IDC_IPADDRESS_CMS               1049
#define IDC_STATIC_CMS_PORT             1050
#define IDC_EDIT_CMS_PORT               1051
#define IDC_BUTTON_CMS_SET              1052
#define IDC_EDIT_WIFI_SSID              1053
#define IDC_STATIC_DEVICE_DESC          1054
#define IDC_STATIC_SADP_VERSION         1055
#define IDC_STATIC_VERSION_INFO         1056
#define IDC_STATIC_DEVICE_DESC2         1057
#define IDC_BTN_REFRESH                 1058
#define IDC_BTN_RESTORE_PASSWORD        1059
#define IDC_EDIT_DEV_TYPE               1059
#define IDC_BUTTON_DEFAULT_PW_UP        1060
#define IDC_BTN_MAIL_BOX_RESET_PW       1060
#define IDC_SYNC_IPC_PW                 1061
#define IDC_STATIC_PUID3                1061
#define IDC_STATIC_INPUT_STRING         1062
#define IDC_EDIT_WIFI_PASSWORD          1062
#define IDC_STATIC_INPUT_PASSWORD       1063
#define IDC_COM_DISPLAYRULE             1064
#define IDC_STATIC_RESET_PASSWORD_TYPE  1064
#define IDC_BTN_SET_DISPLAY_RULE        1065
#define IDC_SYNC_IPC_PW2                1065
#define IDC_CUSTOM_FUNC                 1066
#define IDC_BTN_CHECK                   1066
#define IDC_BTN_GET_RESET_TYPE          1066
#define IDC_CMB_MARK1                   1067
#define IDC_CHECK_HCPLATFORM_STATUS     1067
#define IDC_EDIT_TOTAL_DISK             1067
#define IDC_COM_DISPLAYRULE2            1067
#define IDC_COM_WIFIMODE                1067
#define IDC_CB_GUID                     1067
#define IDC_CMB_RESET_PASSWORD_TYPE     1068
#define IDC_BUTTON7                     1068
#define IDC_BTN_HCPLATFORM              1068
#define IDC_EDIT_GOOD_DISK              1068
#define IDC_EDIT_SERIAL_1               1069
#define IDC_BTN_BIND                    1069
#define IDC_EDIT_CPU                    1069
#define IDC_CB_SECURITY_QUESTION2       1069
#define IDC_CB_SECURITY_QUESTION        1069
#define IDC_EDIT_SERIAL_2               1070
#define IDC_BTN_WIFI_REGION             1070
#define IDC_EDIT_MEMORY                 1070
#define IDC_CB_SECURITY_MAILBOX         1070
#define IDC_EDIT_SERIAL_3               1071
#define IDC_EDIT_PROGRESS               1071
#define IDC_BTN_WIFI_PARAM_CFG          1071
#define IDC_CB_HC                       1071
#define IDC_EDIT_SERIAL_4               1072
#define IDC_COM_TEMPERATURE_STATE       1072
#define IDC_BTN_CONFIG                  1072
#define IDC_CMB_MARK2                   1073
#define IDC_EDIT_SERIAL_5               1073
#define IDC_COM_FAN_STATE               1073
#define IDC_BTN_WIFI_PARAM_CHECK        1073
#define IDC_CMB_MARK3                   1074
#define IDC_EDIT_SERIAL_6               1074
#define IDC_COM_POWER_STATE             1074
#define IDC_BTN_UNBIND                  1074
#define IDC_CMB_MARK4                   1075
#define IDC_EDIT_SERIAL_7               1075
#define IDC_BTN_CHECK2                  1075
#define IDC_BTN_CHECK_BY_MAC            1075
#define IDC_BTN_UNBIND_DEL_USER         1075
#define IDC_CMB_MARK5                   1076
#define IDC_EDIT_SERIAL_8               1076
#define IDC_BTN_SET_TOKEN               1076
#define IDC_CMB_MARK6                   1077
#define IDC_EDIT_SERIAL_9               1077
#define IDC_CMB_MARK7                   1078
#define IDC_EDIT_SERIAL_10              1078
#define IDC_CMB_MARK8                   1079
#define IDC_EDIT_SERIAL_11              1079
#define IDC_EDIT_TOTAL_NETWORK_PORT     1079
#define IDC_CMB_MARK9                   1080
#define IDC_EDIT_SERIAL_12              1080
#define IDC_EDIT_CONNECT_NETWORK_PORT   1080
#define IDC_CMB_MARK10                  1081
#define IDC_EDIT_SERIAL_13              1081
#define IDC_COM_SAS_CONNECT_STATE       1081
#define IDC_CMB_MARK11                  1082
#define IDC_EDIT_SERIAL_14              1082
#define IDC_CMB_MARK12                  1083
#define IDC_EDIT_SERIAL_15              1083
#define IDC_CMB_MARK13                  1084
#define IDC_BTN_SET_BIND_LIST           1084
#define IDC_CMB_MARK14                  1085
#define IDC_BTN_GET_BIND_LIST           1085
#define IDC_CMB_MARK15                  1086
#define IDC_UNBIND_ALL                  1086
#define IDC_SERIAL_1                    1087
#define IDC_CHECK_WIFI_ENHANCEMENT      1087
#define IDC_CMB_MARK16                  1087
#define IDC_SERIAL_2                    1088
#define IDC_COMBO_REGION                1088
#define IDC_CMB_MARK17                  1088
#define IDC_SERIAL_3                    1089
#define IDC_COM_LAMP_ACTION             1089
#define IDC_CMB_MARK18                  1089
#define IDC_SERIAL_4                    1090
#define IDC_BTN_SEND_LAMP               1090
#define IDC_SERIAL_5                    1091
#define IDC_BTN_DISK_LOCATE             1091
#define IDC_SERIAL_6                    1092
#define IDC_BTN_SELF_CHECK              1092
#define IDC_SERIAL_7                    1093
#define IDC_BTN_EHOME_ENABLE            1093
#define IDC_SERIAL_8                    1094
#define IDC_BTN_ENABLE                  1094
#define IDC_SERIAL_9                    1095
#define IDC_EDIT_EHOME_ENABLE_PASSWORD  1095
#define IDC_SERIAL_10                   1096
#define IDC_EDIT_MAIL_BOX_ADDR          1096
#define IDC_SERIAL_11                   1097
#define ID_SET_MAIL_BOX                 1097
#define IDC_SERIAL_12                   1098
#define IDC_EXPORT_QR_CODES             1098
#define IDC_SERIAL_13                   1099
#define IDC_EDIT_QR_CODES               1099
#define IDC_BTN_EXPORT_FILE2            1099
#define IDC_SERIAL_14                   1100
#define IDC_EDIT_SAFE_CODE              1100
#define IDC_EDIT_INPUT_STRING2          1100
#define IDC_SERIAL_15                   1101
#define IDC_RESET_PASSWORD              1101
#define IDC_BUTTON_STARTV30             1101
#define IDC_BTN_CANCLE                  1102
#define IDC_BUTTON_STARTV40             1102
#define IDC_BUTTON10                    1103
#define IDC_BUTTON_SET_REQINTERVAL      1103
#define IDC_STATIC_INTERVAL             1104
#define IDC_BUTTON_STARTV50             1104
#define IDC_STATIC_UNIT                 1105
#define IDC_BUTTON_SUBNET_INQUERY       1105
#define IDC_BUTTON_CANCEL               1106
#define IDC_COM_SET_FILTER_RULE         1107
#define IDC_STATIC_DEVICENO             1108
#define IDC_EDIT_DEVICE_SERIVAL_NO      1109
#define IDC_STATIC_PASSWORD             1110
#define IDC_BUTTON_SEC_QUE              1110
#define IDC_BUTTON_MAIL_RESET           1111
#define IDC_BUTTON_RESTORE_INACTIVE     1112
#define IDC_BUTTON_SAVE                 1113
#define IDC_BUTTON_PHONE_RESET          1113
#define IDC_STATIC_DEV_SERIAL_NO        1114
#define IDC_BUTTON9                     1115
#define IDC_BUTTON_EXPORT               1116
#define IDC_BUTTON_IMPORT               1117
#define IDC_CHECK_SYNC                  1118
#define IDC_BUTTON_RESET2               1120
#define IDC_CHECK1                      1121
#define IDC_BUTTON11                    1122
#define IDC_EDIT_EZVIZ_TOKEN            1123
#define IDC_BTN_EZVIZ_TOKEN             1124
#define IDC_EDIT_EZVIZ_TOKEN_PASSWORD   1125
#define IDC_BTN_SEARCH                  1125

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
